//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory_add
    {
        public int Id { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_word { get; set; }
        public Nullable<System.DateTime> dDatetime { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblWord tblWord { get; set; }
    }
}
