//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWord()
        {
            this.tblHistory_add = new HashSet<tblHistory_add>();
            this.tblHistory_search = new HashSet<tblHistory_search>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Language { get; set; }
        public Nullable<int> Id_Language_trans { get; set; }
        public Nullable<int> Id_wordtype { get; set; }
        public Nullable<int> Id_user { get; set; }
        public string sWord { get; set; }
        public string sExample { get; set; }
        public string sDefinition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistory_add> tblHistory_add { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistory_search> tblHistory_search { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual tblLanguage tblLanguage1 { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblWord_type tblWord_type { get; set; }
    }
}
